<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan</name>
   <tag></tag>
   <elementGuidId>da499fbf-0b4c-4e39-b513-23ad70ec4f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-20.btn.btn-green.btn-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d89205f0-aee7-4a58-81e7-498ace828f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f8c0c98a-d8c1-4969-a886-9627f9235e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-20 btn btn-green btn-block</value>
      <webElementGuid>0d96123a-e010-4103-9d65-640476622e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan Perubahan</value>
      <webElementGuid>434aa16d-e976-42b1-a54c-79d9c0753453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-container list-menu-view&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;container-fluid margin-top20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9 col-xl-9 center-block no-float&quot;]/div[@class=&quot;box-widget widget-module&quot;]/div[@class=&quot;widget-container&quot;]/div[@class=&quot;widget-block&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group text-right margin-top20&quot;]/div[@class=&quot;col-md-9 px-40&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-4 col-md-4 col-lg-4&quot;]/button[@class=&quot;px-20 btn btn-green btn-block&quot;]</value>
      <webElementGuid>7937ef87-57e1-40db-ad23-01393c1ef8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>637c978e-187d-4b9d-bd99-9a503c32e580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Email'])[1]/following::button[1]</value>
      <webElementGuid>a410a06f-865b-4980-afe3-8e5aea5488cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[2]</value>
      <webElementGuid>a5639f8d-4a10-43e5-ab97-b27104a89869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Password'])[2]/preceding::button[3]</value>
      <webElementGuid>2bb0b8b3-e786-4110-bbc1-eb72f900cd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Lama'])[1]/preceding::button[3]</value>
      <webElementGuid>629aff71-ec02-47c9-bdb5-a29716b12d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan Perubahan']/parent::*</value>
      <webElementGuid>12cb9b72-1a62-4259-8245-829068f15b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/button</value>
      <webElementGuid>f436b758-e628-4d4e-bc12-69c18e11e7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Simpan Perubahan' or . = 'Simpan Perubahan')]</value>
      <webElementGuid>5fda9f69-3450-4610-b652-dbd486efe1c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
