<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_coba dev_ico-chevron-thin-down</name>
   <tag></tag>
   <elementGuidId>9d27852d-5dca-4f48-9cf1-e4b88a798801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='arrow']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ico-chevron-thin-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb5b350b-6331-4884-9bbf-842153f1d7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-chevron-thin-down</value>
      <webElementGuid>b6316474-a199-4cff-93b3-6e4c06af2266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrow&quot;)/span[@class=&quot;ico-chevron-thin-down&quot;]</value>
      <webElementGuid>24e99559-dd98-4898-866c-2a98a4fbfe60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='arrow']/span</value>
      <webElementGuid>4b9e61ae-8354-4bcd-afea-e46553a1c1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>b4eb5c88-7e66-4408-92ab-38504c84c22f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
