<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Development_idperusahaan</name>
   <tag></tag>
   <elementGuidId>fb138537-e3f5-4194-9c63-d1e09f808385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='idperusahaan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;idperusahaan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3106a177-2047-4c21-8248-bbcc4a027d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adf634b0-f726-4f75-836a-3ce3b77e4cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input</value>
      <webElementGuid>60ec8beb-91a0-4c5f-8538-e492be809b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Perusahaan</value>
      <webElementGuid>f6897259-d834-4487-a69e-e9bb704f1c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idperusahaan</value>
      <webElementGuid>70f55fbf-9bba-4f93-aa6f-5d4fc134cb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>341b7e19-f99a-44e5-acd7-439107e9d011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;container is-login&quot;]/div[@class=&quot;form__container&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;form__group has-icon&quot;]/input[@class=&quot;form__input&quot;]</value>
      <webElementGuid>845b92b5-b253-469e-a279-a64017f21be4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='idperusahaan']</value>
      <webElementGuid>d3e115ed-8cd3-407c-b158-0d34b43bc562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ec5fd1cd-2cfa-4a09-9041-3cc38a22fea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama Perusahaan' and @name = 'idperusahaan']</value>
      <webElementGuid>acb5ea8a-ce4a-46bb-baf5-cf7663dc9ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
